version: '3.8'
services:
  # 1. 문지기 Nginx 추가
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf # 설정 파일 연결
    depends_on:
      - app
    networks:
      - backend-net

  # 2. 기존 오라클 DB
  oracle-db:
    image: gvenzl/oracle-xe:latest
    container_name: my-secure-oracle
    environment:
      - ORACLE_PASSWORD=${ORACLE_ROOT_PASSWORD}
      - APP_USER=${DB_USERNAME}
      - APP_USER_PASSWORD=${DB_USERPASSWORD}
    volumes:
      - oracle_data:/opt/oracle/oradata
    networks:
      - backend-net

  # 3. 기존 스프링 App (수정됨)
  app:
    build: .
    # container_name: spring-app
    # ports: - "80:8080" 부분을 삭제합니다. (Nginx가 80을 쓰기 때문)
    expose:
      - "8080" # 외부엔 안 보이고 Nginx만 접근 가능
    depends_on:
      - oracle-db
    environment:
      - DB_HOST=oracle-db
      - DB_USERNAME=${DB_USERNAME}
      - DB_USERPASSWORD=${DB_USERPASSWORD}
      - MAP_API_KEY=${MAP_API_KEY}
      - MAIL_ID=${MAIL_ID}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
    networks:
      - backend-net

networks:
  backend-net:
    driver: bridge

volumes:
  oracle_data: